DROP TABLE IF EXISTS "Category";
CREATE TABLE "Category" (
	"ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , 
	"Name" VARCHAR NOT NULL,
	"CreatedOn" DATETIME NOT NULL , 
	"CreatedBy" INTEGER NOT NULL , 
	"ModifiedOn" DATETIME NOT NULL , 
	"ModifiedBy" INTEGER NOT NULL 
);

DROP TABLE IF EXISTS "Comment";
CREATE TABLE "Comment" 
(
	"ID" INTEGER PRIMARY KEY  NOT NULL ,
	"PostID" INTEGER NOT NULL ,
	"Body" VARCHAR NOT NULL ,
	"CreatedOn" DATETIME NOT NULL , 
	"CreatedBy" INTEGER NOT NULL , 
	"ModifiedOn" DATETIME NOT NULL , 
	"ModifiedBy" INTEGER NOT NULL
);

DROP TABLE IF EXISTS "Post";
CREATE TABLE "Post" 
(
	"ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
	"CategoryID" INTEGER NOT NULL , 
	"Subject" VARCHAR NOT NULL , 
	"Body" TEXT NOT NULL , 
	"CreatedOn" DATETIME NOT NULL , 
	"CreatedBy" INTEGER NOT NULL , 
	"ModifiedOn" DATETIME NOT NULL , 
	"ModifiedBy" INTEGER NOT NULL 
);

DROP TABLE IF EXISTS "User";
CREATE TABLE "User" 
(
	"ID" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , 
	"Name" VARCHAR NOT NULL , 
	"CreatedOn" DATETIME NOT NULL , 
	"CreatedBy" INTEGER NOT NULL , 
	"ModifiedOn" DATETIME NOT NULL , 
	"ModifiedBy" INTEGER NOT NULL 
);
